---
# Copyright 2022, Rackspace US, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in witing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This playbook cleans the Terraform directory only once we're sure
# the resources are no longer needed.

- name: Clean environment on destroy
  hosts: localhost
  connection: local
  gather_facts: false
  any_errors_fatal: true
  vars_files:
    - vars/main.yml
  tasks:
    - name: Read Terraform state file
      ansible.builtin.shell: "cat {{ playbook_dir }}/../terraform/terraform.tfstate"
      register: result

    - name: Save JSON data to variable
      set_fact:
        jsondata: "{{ result.stdout | from_json }}"

    - name: Grab Terraform resources
      set_fact:
        tf_resources: "{{ jsondata | json_query(jmesquery) }}"
      vars:
        jmesquery: 'resources'

    - name: Remove Terraform files
      ansible.builtin.file:
        path: "{{ item }}"
        state: absent
      with_items:
        - "{{ playbook_dir }}/../terraform/000-variables.tf"
        - "{{ playbook_dir }}/../terraform/010-sshkey.tf"
        - "{{ playbook_dir }}/../terraform/020-network.tf.tf"
        - "{{ playbook_dir }}/../terraform/030-security_group.tf.tf"
        - "{{ playbook_dir }}/../terraform/040-flavor.tf"
        - "{{ playbook_dir }}/../terraform/050-image.tf"
        - "{{ playbook_dir }}/../terraform/060-instance_controller.tf"
        - "{{ playbook_dir }}/../terraform/061-instance_compute.tf"
        - "{{ playbook_dir }}/../terraform/062-instance_loadbalancer.tf"
        - "{{ playbook_dir }}/../terraform/063-instance_deployer.tf"
        - "{{ playbook_dir }}/../terraform/064-instance_ceph.tf"
        - "{{ playbook_dir }}/../terraform/100-inventory.tf"
        - "{{ playbook_dir }}/../terraform/101-ansible-vars.tf"
        - "{{ playbook_dir }}/../terraform/105-private-key.tf.tf"
      when: tf_resources | length <= 0
