---
# Copyright 2022, Rackspace US, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in witing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

- name: Setup deploy host
  hosts: deploy_hosts
  gather_facts: true
  environment: "{{ deployment_environment_variables | default({}) }}"
  become: true
  vars_files:
  - vars/main.yml
  tags:
    - deploy-osa
  tasks:
    - debug:
        msg: "{{ playbook_dir }}/vars/{{ ansible_os_family | lower }}.yml"

    - name: Gather variables for each operating system
      include_vars: "{{ item }}"
      with_first_found:
        - "{{ playbook_dir }}/vars/{{ ansible_distribution | lower }}-{{ ansible_distribution_version | lower }}.yml"
        - "{{ playbook_dir }}/vars/{{ ansible_distribution | lower }}-{{ ansible_distribution_major_version | lower }}.yml"
        - "{{ playbook_dir }}/vars/{{ ansible_os_family | lower }}-{{ ansible_distribution_major_version | lower }}.yml"
        - "{{ playbook_dir }}/vars/{{ ansible_distribution | lower }}.yml"
        - "{{ playbook_dir }}/vars/{{ ansible_os_family | lower }}.yml"
      tags:
        - always

    - name: Get RPC OpenStack Ops
      git:
        repo: "{{ rpc_ops_repo | default('https://github.com/rcbops/openstack-ops') }}"
        dest: /opt/openstack-ops
        version: "{{ osa_branch | default('master') }}"
      when:
        - pre_config_osa | default(true) | bool
        - clone_osa | default(true) | bool

    - name: Finished notice
      debug:
        msg: |
          RPC openstack-ops repo has been downloaded. To proceed, login to the deploy host ({{ groups['deploy_hosts'][0] }})
          at {{ ansible_ssh_host }} and run the the following command(s):

          cd /opt/openstack-ops; SKIP_PROMPTS=true OSA_ENV=lab1 OSA_ENV_LCASE=lab1 OSA_RELEASE=23.4.4 OSA_RUN_PLAY=false RPCO_CONFIG_BRANCH=master scripts/deploy-rpco.sh

          Once complete, come back and run the "setup-rpc.sh" bash script from the MNAIOv2 directory.
      when:
        - run_osa | default(true) | bool
